auth:
  auth-memory:
    users:
      foo:
        name: test
        password: test
store:
  memory:
    limit: 10000
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
    maxage: 60s

packages:
  '@*/*':
    access: $all
    publish: $all
    proxy: npmjs
  '**':
    access: $all
    publish: $all
    proxy: npmjs
middlewares:
  audit:
    enabled: true
logs:
 - {type: stdout, format: pretty, level: debug}
